name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Ellenőrizd ki a repót
    - name: Check out the repository
      uses: actions/checkout@v2

    # Frissítsd a pip3-at
    - name: Upgrade pip3
      run: |
        python3 -m pip install --upgrade pip

    # Futtasd le a Docker build parancsot
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my_python_app:latest

    # Kérdezd le a `ibm-cos-sdk` elérhető verzióit pip3-al
    - name: Check available versions for ibm-cos-sdk with pip3
      run: |
        docker run my_python_app:latest pip3 search ibm-cos-sdk || true

    # Telepítsd az `ibm-cos-sdk` csomagot, és naplózd az esetleges hibákat
    - name: Install ibm-cos-sdk with pip3
      run: |
        docker run my_python_app:latest pip3 install --no-cache-dir ibm-cos-sdk --extra-index-url https://pypi.org/simple || echo "Failed to install ibm-cos-sdk"

    # Telepítsd a csomagokat req.txt fájlból pip3-al
    - name: Install requirements from req.txt with pip3
      run: |
        docker run my_python_app:latest pip3 install --no-cache-dir -r req.txt --extra-index-url https://pypi.org/simple || echo "Could not install requirements"

    # Teszteld a Docker image-et (például futtasd a Python programot)
    - name: Run container from Docker image
      run: |
        docker run my_python_app:latest


