name: Docker Test

on:
  push:
    branches:
      - main  # You can change this to any branch you want to monitor
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my_python_app:latest

    - name: Run Docker container
      run: docker run -d -p 8080:8080 my_python_app:latest

    - name: Test the application
      run: |
        sleep 5
        curl http://localhost:8080/upload -X POST -d "file=output.txt"
