name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Upgrade pip3
      run: |
        python3 -m pip install --upgrade pip

    - name: Display req.txt content
      run: cat req.txt

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my_python_app:latest

    - name: Check available versions for ibm_boto3 with pip3
      run: |
        docker run my_python_app:latest pip3 index versions ibm_boto3

    - name: Run pip3 install with alternative index URL
      run: |
        docker run my_python_app:latest pip3 install --no-cache-dir --extra-index-url https://pypi.org/simple ibm_boto3

    - name: Install requirements from req.txt with pip3
      run: |
        docker run my_python_app:latest pip3 install --no-cache-dir -r req.txt --extra-index-url https://pypi.org/simple --extra-index-url https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/yum/ibm-ai/python || echo "Could not install requirements"

    - name: Display pip version and available packages
      run: |
        docker run my_python_app:latest pip --version
        docker run my_python_app:latest pip list

    - name: Run container from Docker image
      run: |
        docker run my_python_app:latest

    - name: Clean up Docker
      run: |
        docker rmi my_python_app:latest
